version: '3'

services:
  mongo:
    image: mongo
    container_name: lisense-mongodb
    ports:
      - '8080:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  backend:
    build: .
    command: python3 server.py
    ports:
      - '5000:5000'
    depends_on:
      - mongo
